---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: "13.6.4"
  always_update_cookbooks: true
  environments_path: test/environments
  client_rb:
    environment: _default

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    data_bag_path: 'test/integration/data_bags'
    run_list:
      - recipe[redirects::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
