[local_phases]
unit = "echo skipping"
lint = 'cookstyle --display-cop-names --extra-details'
syntax = "foodcritic ."
smoke = "chef exec kitchen verify"
provision = "echo skipping"
deploy = "echo skipping"
functional = "echo skipping"
cleanup = "echo skipping"
